Update coding_python.yml

diff --git a/.github/workflows/coding_python.yml b/.github/workflows/coding_python.yml
--- a/.github/workflows/coding_python.yml
+++ b/.github/workflows/coding_python.yml
@@ -45,11 +45,14 @@ jobs:
             black $line
           done < ${{ github.workspace }}/changed_projects_folder.txt
 
+          git diff -- "*.py" > patch.diff
+
       - name: Upload Result
+        id: auto_fix
         uses: actions/upload-artifact@v4
         with:
-          name: auto_fixed
-          path: projects
+          name: git_patch
+          path: projects/patch.diff
           
       - name: run flake8
         run: |
@@ -57,6 +60,16 @@ jobs:
           while IFS= read -r line; do
             echo ==========================================
             echo "Checking code convention for: $line"
-            flake8 $line
+            flake8 $line >> ${{ github.workspace }}/flake8_log.txt
           done < ${{ github.workspace }}/changed_projects_folder.txt
+        continue-on-error: true
+
+      - name: Check status
+        run: |
+          if [ -s "${{ github.workspace }}/flake8_log.txt" ]; then
+            echo "Success check code convention"
+          else
+            echo "Failure check code convention"
+            echo "Download auto-fix package here: ${{ steps.auto_fix.outputs.artifact-url }}"
+            exit 1
           
